import './globals.css'
import { Navigation } from './components/navigation'

export const metadata = {
  title: 'Mi aplicación Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
